spring.application.name: file-service
server.port: 9092
file-data-service.host: localhost
federated-graphql.schema-path: src/main/resources/schema

federated-graphql:
  data-fetcher-sources:
    GetFilesRemoteDataFetcher:
      path: src/main/resources/remotecode/com/hayden/fileservice/data_fetcher/GetFilesRemoteDataFetcher.java
      field-name: *
      package-name: com.hayden.fileservice.data_fetcher
      mime-type: files/*